name: Workflow 2
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: STEP 1
        run: |
          echo -e "PEPE" > .github/PRUEBA_ACTIONS-README.MD
          git add .github/PRUEBA_ACTIONS-README.MD
          git commit --message="Update README.md"
          git push
    
