name: Primer Workflow propio
#Este workflow se activa cuando se realiza un push en la rama 'feature'
on: 
 pull_request:
   branches:
    - main
jobs:
  build:
    name: Post Hello World comment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
    


  
